baseURL = 'https://saferefuge.pl'
defaultContentLanguage = 'en'
title = 'project safe refuge'
canonifyurls = false
relativeURLs = true


[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.jp]
    languageName = "日本語"
    weight = 2
  [languages.it]
    languageName = "italiano"
    weight = 3